import type { Weapon } from '../types/weapon';

export const initialWeapons: Weapon[] = [
  {
    id: 'weapon-autopistol',
    name: 'Autopistol',
    cost: 15,
    rules: ['Pistol', 'Rapid Fire (1)'],
    range: { short: 6, long: 12 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-laspistol',
    name: 'Laspistol',
    cost: 10,
    rules: ['Pistol', 'Plentiful'],
    range: { short: 8, long: 16 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-stubgun',
    name: 'Stub Gun',
    cost: 5,
    rules: ['Pistol', 'Plentiful'],
    range: { short: 6, long: 12 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-autogun',
    name: 'Autogun',
    cost: 25,
    rules: ['Basic', 'Rapid Fire (1)'],
    range: { short: 12, long: 24 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-lasgun',
    name: 'Lasgun',
    cost: 20,
    rules: ['Basic', 'Plentiful'],
    range: { short: 16, long: 32 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-shotgun',
    name: 'Shotgun',
    cost: 30,
    rules: ['Basic', 'Scattershot'],
    range: { short: 8, long: 16 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-boltgun',
    name: 'Boltgun',
    cost: 60,
    rules: ['Basic', 'Rapid Fire (1)', 'Scarce'],
    range: { short: 16, long: 32 },
    accuracy: { short: 4, long: 5 },
    strength: 4,
    armorPiercing: 1,
    damage: 2,
    ammunition: 6,
  },
  {
    id: 'weapon-plasma-gun',
    name: 'Plasma Gun',
    cost: 80,
    rules: ['Basic', 'Scarce', 'Unstable'],
    range: { short: 12, long: 24 },
    accuracy: { short: 4, long: 5 },
    strength: 5,
    armorPiercing: 2,
    damage: 2,
    ammunition: 6,
  },
  {
    id: 'weapon-meltagun',
    name: 'Meltagun',
    cost: 85,
    rules: ['Basic', 'Scarce', 'Melta'],
    range: { short: 6, long: 12 },
    accuracy: { short: 4, long: 5 },
    strength: 6,
    armorPiercing: 3,
    damage: 2,
    ammunition: 6,
  },
  {
    id: 'weapon-flamer',
    name: 'Flamer',
    cost: 70,
    rules: ['Basic', 'Template', 'Scarce'],
    range: { short: 8, long: 8 },
    accuracy: { short: 4, long: 4 },
    strength: 4,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-grenade-launcher',
    name: 'Grenade Launcher',
    cost: 75,
    rules: ['Basic', 'Blast (3")', 'Scarce'],
    range: { short: 12, long: 24 },
    accuracy: { short: 4, long: 5 },
    strength: 3,
    armorPiercing: 1,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-heavy-bolter',
    name: 'Heavy Bolter',
    cost: 120,
    rules: ['Heavy', 'Rapid Fire (2)', 'Scarce'],
    range: { short: 16, long: 32 },
    accuracy: { short: 4, long: 5 },
    strength: 4,
    armorPiercing: 1,
    damage: 2,
    ammunition: 6,
  },
  {
    id: 'weapon-heavy-stubber',
    name: 'Heavy Stubber',
    cost: 90,
    rules: ['Heavy', 'Rapid Fire (2)'],
    range: { short: 16, long: 32 },
    accuracy: { short: 4, long: 5 },
    strength: 4,
    armorPiercing: 0,
    damage: 1,
    ammunition: 6,
  },
  {
    id: 'weapon-lascannon',
    name: 'Lascannon',
    cost: 150,
    rules: ['Heavy', 'Scarce'],
    range: { short: 24, long: 48 },
    accuracy: { short: 4, long: 5 },
    strength: 6,
    armorPiercing: 3,
    damage: 2,
    ammunition: 6,
  },
  {
    id: 'weapon-missile-launcher',
    name: 'Missile Launcher',
    cost: 140,
    rules: ['Heavy', 'Blast (3")', 'Scarce'],
    range: { short: 24, long: 48 },
    accuracy: { short: 4, long: 5 },
    strength: 5,
    armorPiercing: 2,
    damage: 2,
    ammunition: 6,
  },
]; 